# Sveltia CMS configuration

# This is where we configure the CMS repo and its collections and fields
# Sveltia CMS generally follows the Decap CMS configuration spec
# Decap CMS docs: https://decapcms.org/docs/intro/
# Sveltia CMS docs: https://github.com/sveltia/sveltia-cms#features

# Enter your GitHub repo path and branch (defaults to master)
backend:
  name: github
  repo: henriksommerfeld/food-sveltekit
  branch: main
  automatic_deployments: true
  base_url: https://auth.recept.sommerfeld.nu

# The folder used to store uploaded images
media_folder: 'static/uploads'

media_libraries:
  stock_assets:
    providers: []
  default:
    config:
      max_file_size: 10240000 # 10 MB default: Infinity
      slugify_filename: true # default: false

# The CMS collections and their fields
collections:
  - name: 'recept'
    label: 'Recept'
    label_singular: 'Recept'
    icon: 'menu_book'
    folder: 'src/recept'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Beskrivning', name: description, widget: string, required: false }
      - { label: 'Redskap', name: tools, widget: string, hint: '', required: false }
      - {
          label: 'Dold',
          name: 'hidden',
          widget: 'boolean',
          default: false,
          hint: 'Om du vill spara utan att publicera kan du göra receptet dolt här.'
        }
      - {
          label: 'Kategori',
          name: 'category',
          widget: 'select',
          multiple: false,
          options: ['Frukost', 'Förrätt', 'Huvudrätt', 'Tillbehör', 'Efterrätt', 'Bakning'],
          default: 'Huvudrätt',
          hint: 'Kategorin blir Huvudrätt om inget anges. Välj detta om inget annat passar in.'
        }
      - {
          label: 'Bild',
          name: 'featuredimage',
          widget: 'image',
          hint: 'Det behövs en bild, men du kan välja en standardbild i biblioteket.'
        }
      - {
          label: 'Portioner/antal',
          name: 'servings',
          widget: number,
          min: 0,
          hint: 'Ange hur många portioner receptet är tänkt för. Är det mer lämpligt att ange antal, ex. 20 bullar, ange då 20 och skriv något om detta i beskrivningen ovan.'
        }
      - {
          label: 'Portioner eller annat',
          name: 'servingslabel',
          widget: 'string',
          default: 'portioner',
          hint: '"portioner" används om inget anges. Ex. "bullar", "liter"'
        }
      - {
          label: 'Grupper av ingredienser',
          name: 'ingredients',
          widget: 'list',
          required: false,
          fields:
            [
              {
                label: 'Delmoment, ex. "Sås"',
                name: 'partingredients',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Rubrik',
                      name: 'partingredientsname',
                      widget: 'string',
                      hint: 'Underrubrik för ett delmoment, ex. "Aioli". Visas inte om det inte finns flera delmoment.'
                    },
                    {
                      label: 'Ingredienslista, delmoment',
                      name: 'partingredientslist',
                      widget: 'list',
                      required: false,
                      fields:
                        [
                          {
                            label: 'Ingrediens',
                            name: 'ingredient',
                            widget: 'object',
                            fields:
                              [
                                {
                                  label: 'Mängd',
                                  name: 'ingredientamount',
                                  widget: 'number',
                                  value_type: 'float',
                                  min: 0,
                                  hint: 'Ange 0 om du inte vill visa någon mängd, ex. "salt"'
                                },
                                {
                                  label: 'Måttenhet',
                                  name: 'unit',
                                  widget: select,
                                  options:
                                    [
                                      { label: 'Styck (st)', value: 'st' },
                                      { label: 'Liter (l)', value: 'l' },
                                      { label: 'Deciliter (dl)', value: 'dl' },
                                      { label: 'Centiliter (cl)', value: 'cl' },
                                      { label: 'Milliliter (ml)', value: 'ml' },
                                      { label: 'Matsked (msk)', value: 'msk' },
                                      { label: 'Tesked (tsk)', value: 'tsk' },
                                      { label: 'Gram (g)', value: 'g' },
                                      { label: 'Hekto (hg)', value: 'hg' },
                                      { label: 'Kilo (kg)', value: 'kg' }
                                    ]
                                },
                                { label: 'Namn', name: 'ingredientname', widget: 'string' }
                              ]
                          }
                        ]
                    }
                  ]
              }
            ]
        }
      - {
          label: 'Grupper av instruktioner',
          name: 'instructions',
          widget: 'list',
          required: false,
          fields:
            [
              {
                label: 'Grupp av instruktioner',
                name: 'partinstructions',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Rubrik',
                      name: partinstructionsname,
                      widget: string,
                      hint: 'Ex. "Sås". Kan lämnas tom om det bara finns ett moment.',
                      required: false
                    },
                    {
                      label: 'Instruktioner för delmoment',
                      name: 'partinstructionslist',
                      widget: 'list',
                      required: false,
                      fields: [{ label: 'Instruktion', name: instruction, widget: 'string' }]
                    }
                  ]
              }
            ]
        }
      - {
          label: 'Avslutande ord',
          name: 'body',
          widget: 'markdown',
          buttons: ['bold', 'italic', 'link'],
          required: false
        }
      - {
          label: 'Väntetid',
          name: 'timepassive',
          widget: 'object',
          fields:
            [
              { label: 'Dagar', name: 'dayspassive', widget: number, default: 0, min: 0 },
              { label: 'Timmar', name: 'hourspassive', widget: number, default: 0, min: 0 },
              { label: 'Minuter', name: 'minutespassive', widget: number, default: 0, min: 0 }
            ]
        }
      - {
          label: 'Aktiv tillagningstid',
          name: 'timeactive',
          widget: 'object',
          fields:
            [
              { label: 'Timmar', name: 'hoursactive', widget: number, default: 0, min: 0 },
              { label: 'Minuter', name: 'minutesactive', widget: number, default: 0, min: 0 }
            ]
        }
      - {
          label: 'Taggar',
          label_singular: 'Tagg',
          name: 'tags',
          widget: 'list',
          required: false,
          hint: 'Taggarna är till för att kunna hitta andra recept taggade med samma sak, så ange inte för många.'
        }
